var charactersData = {
	group1: [
		{ name: 'Роджер', image: 'img/', link: 'characters/roger.html' },
		{ name: 'Шанкс', image: 'img/', link: 'characters/shansk.html' },
		{ name: 'Бекман', image: 'img/', link: 'characters/beckman.html' },
		{ name: 'Лаки', image: 'img/', link: 'characters/laki.html' },
		{ name: 'Ясопп', image: 'img/', link: 'characters/yassop.html' },
		{ name: 'Макино', image: 'img/', link: 'characters/makino.html' },
		{ name: 'Вул', image: 'img/', link: 'characters/vul.html' },
		{ name: 'Хигума', image: 'img/', link: 'characters/higuma.html' },
		{ name: 'Коби', image: 'img/', link: 'characters/kobi.html' },
		{ name: 'Альвида', image: 'img/', link: 'characters/alvida.html' },
		{ name: 'Хельмеппо', image: 'img/', link: 'characters/helmeppo.html' },
		{ name: 'Moрнан', image: 'img/', link: 'characters/.html' },
		{ name: 'Косиро', image: 'img/', link: 'characters/.html' },
		{ name: 'Куина', image: 'img/', link: 'characters/.html' },
		{ name: 'Домо-кун', image: 'img/', link: 'characters/.html' },
		{ name: 'Кабаджи', image: 'img/', link: 'characters/.html' },
		{ name: 'Багги', image: 'img/', link: 'characters/.html' },
		{ name: 'Ричи', image: 'img/', link: 'characters/.html' },
		{ name: 'Моджи', image: 'img/', link: 'characters/.html' },
		{ name: 'Будл', image: 'img/', link: 'characters/.html' },
		{ name: 'Шушу', image: 'img/', link: 'characters/.html' },
		{ name: 'Рейли', image: 'img/', link: 'characters/.html' },
		{ name: 'Гаймон', image: 'img/', link: 'characters/.html' },
		{ name: 'Куро', image: 'img/', link: 'characters/.html' },
		{ name: 'Кая', image: 'img/', link: 'characters/.html' },
		{ name: 'Пииман', image: 'img/', link: 'characters/.html' },
		{ name: 'Таманэги', image: 'img/', link: 'characters/.html' },
		{ name: 'Нинжин', image: 'img/', link: 'characters/.html' },
		{ name: 'Усопп', image: 'img/', link: 'characters/.html' },
		{ name: 'Мерри', image: 'img/', link: 'characters/.html' },
		{ name: 'Джанго', image: 'img/', link: 'characters/.html' },
		{ name: 'Бути', image: 'img/', link: 'characters/.html' },
		{ name: 'Сям', image: 'img/', link: 'characters/.html' },
		{ name: 'Банкина', image: 'img/', link: 'characters/.html' },
		{ name: 'Ёсаку', image: 'img/', link: 'characters/.html' },
		{ name: 'Джонни', image: 'img/', link: 'characters/.html' },
		{ name: 'Зефф', image: 'img/', link: 'characters/.html' },
		{ name: 'Фулботи', image: 'img/', link: 'characters/.html' },
		{ name: 'Патти', image: 'img/', link: 'characters/.html' },
		{ name: 'Гин', image: 'img/', link: 'characters/.html' },
		{ name: 'Пандамен', image: 'img/', link: 'characters/.html' },
		{ name: 'Криг', image: 'img/', link: 'characters/.html' },
		{ name: 'Михоук', image: 'img/', link: 'characters/.html' },
		{ name: 'Перл', image: 'img/', link: 'characters/.html' },
		{ name: 'Чу', image: 'img/', link: 'characters/.html' },
		{ name: 'Нэдзуми', image: 'img/', link: 'characters/.html' },
		{ name: 'Хаттян', image: 'img/', link: 'characters/.html' },
		{ name: 'Курооби', image: 'img/', link: 'characters/.html' },
		{ name: 'Арлонг', image: 'img/', link: 'characters/.html' },
		{ name: 'Ноджико', image: 'img/', link: 'characters/.html' },
		{ name: 'Ганзо', image: 'img/', link: 'characters/.html' },
		{ name: 'Мому', image: 'img/', link: 'characters/.html' },
		{ name: 'Белл-мера', image: 'img/', link: 'characters/.html' },
		{ name: 'Нако', image: 'img/', link: 'characters/.html' },
		{ name: 'Богарт', image: 'img/', link: 'characters/.html' },
		{ name: 'Гарп', image: 'img/', link: 'characters/.html' },
		{ name: 'Ташиги', image: 'img/', link: 'characters/.html' },
		{ name: 'Иппон-Мацу', image: 'img/', link: 'characters/.html' },
		{ name: 'Смокер', image: 'img/', link: 'characters/.html' },
		{ name: 'Драгон', image: 'img/', link: 'characters/.html' },
		{ name: 'Крокус', image: 'img/', link: 'characters/.html' },
		{ name: 'Лабун', image: 'img/', link: 'characters/.html' },
		{ name: 'Мистер 9', image: 'img/', link: 'characters/.html' },
		{ name: 'Виви', image: 'img/', link: 'characters/.html' },
		{ name: 'Фарайдей', image: 'img/', link: 'characters/.html' },
		{ name: 'Мистер 13', image: 'img/', link: 'characters/.html' },
		{ name: 'Игарам', image: 'img/', link: 'characters/.html' },
		{ name: 'Мандей', image: 'img/', link: 'characters/.html' },
		{ name: 'Симиджу', image: 'img/', link: 'characters/.html' },
		{ name: 'Кару', image: 'img/', link: 'characters/.html' },
		{ name: 'Мистер 5', image: 'img/', link: 'characters/.html' },
		{ name: 'Валентайн', image: 'img/', link: 'characters/.html' },
		{ name: 'Дорри', image: 'img/', link: 'characters/.html' },
		{ name: 'Броги', image: 'img/', link: 'characters/.html' },
		{ name: 'Голдевник', image: 'img/', link: 'characters/.html' },
		{ name: 'Галдино', image: 'img/', link: 'characters/.html' },
		{ name: 'Крокодайл', image: 'img/', link: 'characters/.html' },
		{ name: 'Бонтян', image: 'img/', link: 'characters/.html' },
		{ name: 'Вапол', image: 'img/', link: 'characters/.html' },
		{ name: 'Чесс', image: 'img/', link: 'characters/.html' },
		{ name: 'Куромаримо', image: 'img/', link: 'characters/.html' },
		{ name: 'Далтон', image: 'img/', link: 'characters/.html' },
		{ name: 'Куреха', image: 'img/', link: 'characters/.html' },
		{ name: 'Робсон', image: 'img/', link: 'characters/.html' },
		{ name: 'Хилюлюк', image: 'img/', link: 'characters/.html' },
		{ name: 'Кобра', image: 'img/', link: 'characters/.html' },
		{ name: 'Эйс', image: 'img/', link: 'characters/.html' },
		{ name: 'Пелл', image: 'img/', link: 'characters/.html' },
		{ name: 'Чака', image: 'img/', link: 'characters/.html' },
		{ name: 'Даблфингер', image: 'img/', link: 'characters/.html' },
		{ name: 'Кристмас', image: 'img/', link: 'characters/.html' },
		{ name: 'Лассу', image: 'img/', link: 'characters/.html' },
		{ name: 'Мистер 4', image: 'img/', link: 'characters/.html' },
		{ name: 'Бонс', image: 'img/', link: 'characters/.html' },
		{ name: 'Мацуге', image: 'img/', link: 'characters/.html' },
		{ name: 'Коза', image: 'img/', link: 'characters/.html' },
		{ name: 'Тото', image: 'img/', link: 'characters/.html' },
		{ name: 'Хина', image: 'img/', link: 'characters/.html' },
		{ name: 'Хасами', image: 'img/', link: 'characters/.html' },
		{ name: 'Кейми', image: 'img/', link: 'characters/.html' },
		{ name: 'Паппг', image: 'img/', link: 'characters/.html' },
	],
	group2: [
		{ name: 'Октопако', image: 'img/', link: 'characters/.html' },
		{ name: 'Фазерсдей', image: 'img/', link: 'characters/.html' },
		{ name: 'Мистер 7', image: 'img/', link: 'characters/.html' },
		{ name: 'Терракотта', image: 'img/', link: 'characters/.html' },
		{ name: 'Тити', image: 'img/', link: 'characters/.html' },
		{ name: 'Маширо', image: 'img/', link: 'characters/.html' },
		{ name: 'Саркис', image: 'img/', link: 'characters/.html' },
		{ name: 'Бёрджесс', image: 'img/', link: 'characters/.html' },
		{ name: 'Огер', image: 'img/', link: 'characters/.html' },
		{ name: 'Беллами', image: 'img/', link: 'characters/.html' },
		{ name: 'Кью', image: 'img/', link: 'characters/.html' },
		{ name: 'Лили', image: 'img/', link: 'characters/.html' },
		{ name: 'Тич', image: 'img/', link: 'characters/.html' },
		{ name: 'Стронгер', image: 'img/', link: 'characters/.html' },
		{ name: 'Седзе', image: 'img/', link: 'characters/.html' },
		{ name: 'Крикет', image: 'img/', link: 'characters/.html' },
		{ name: 'Дофламинго', image: 'img/', link: 'characters/.html' },
		{ name: 'Кума', image: 'img/', link: 'characters/.html' },
		{ name: 'Цуру', image: 'img/', link: 'characters/.html' },
		{ name: 'Джоз', image: 'img/', link: 'characters/.html' },
		{ name: 'Лаффит', image: 'img/', link: 'characters/.html' },
		{ name: 'Сэнгоку', image: 'img/', link: 'characters/.html' },
		{ name: 'Белоус', image: 'img/', link: 'characters/.html' },
		{ name: 'Марко', image: 'img/', link: 'characters/.html' },
		{ name: 'Ганфолл', image: 'img/', link: 'characters/.html' },
		{ name: 'Вайпер', image: 'img/', link: 'characters/.html' },
		{ name: 'Пьерр', image: 'img/', link: 'characters/.html' },
		{ name: 'Су', image: 'img/', link: 'characters/.html' },
		{ name: 'Конис', image: 'img/', link: 'characters/.html' },
		{ name: 'Пагая', image: 'img/', link: 'characters/.html' },
		{ name: 'Гедацу', image: 'img/', link: 'characters/.html' },
		{ name: 'Сатори', image: 'img/', link: 'characters/.html' },
		{ name: 'Холи', image: 'img/', link: 'characters/.html' },
		{ name: 'Шира', image: 'img/', link: 'characters/.html' },
		{ name: 'Фуза', image: 'img/', link: 'characters/.html' },
		{ name: 'Ом', image: 'img/', link: 'characters/.html' },
		{ name: 'Брахам', image: 'img/', link: 'characters/.html' },
		{ name: 'Айса', image: 'img/', link: 'characters/.html' },
		{ name: 'Камакири', image: 'img/', link: 'characters/.html' },
		{ name: 'Яма', image: 'img/', link: 'characters/.html' },
		{ name: 'Энель', image: 'img/', link: 'characters/.html' },
		{ name: 'Нола', image: 'img/', link: 'characters/.html' },
		{ name: 'Калгара', image: 'img/', link: 'characters/.html' },
		{ name: 'Ноланд', image: 'img/', link: 'characters/.html' },
		{ name: 'Касигами', image: 'img/', link: 'characters/.html' },
		{ name: 'Кудзан', image: 'img/', link: 'characters/.html' },
		{ name: 'Шелли', image: 'img/', link: 'characters/.html' },
		{ name: 'Тонджит', image: 'img/', link: 'characters/.html' },
		{ name: 'Фокси', image: 'img/', link: 'characters/.html' },
		{ name: 'Порча', image: 'img/', link: 'characters/.html' },
		{ name: 'Гамбург', image: 'img/', link: 'characters/.html' },
		{ name: 'Итомимиджу', image: 'img/', link: 'characters/.html' },
		{ name: 'Капоти', image: 'img/', link: 'characters/.html' },
		{ name: 'Кибагаэру', image: 'img/', link: 'characters/.html' },
		{ name: 'Монда', image: 'img/', link: 'characters/.html' },
		{ name: 'Тютюн', image: 'img/', link: 'characters/.html' },
		{ name: 'Биг Пан', image: 'img/', link: 'characters/.html' },
		{ name: 'Пиклз', image: 'img/', link: 'characters/.html' },
		{ name: 'Чимни', image: 'img/', link: 'characters/.html' },
		{ name: 'Кокоро', image: 'img/', link: 'characters/.html' },
		{ name: 'Гомбэ', image: 'img/', link: 'characters/.html' },
		{ name: 'Хаттори', image: 'img/', link: 'characters/.html' },
		{ name: 'Паули', image: 'img/', link: 'characters/.html' },
		{ name: 'Лулу', image: 'img/', link: 'characters/.html' },
		{ name: 'Тайлстоун', image: 'img/', link: 'characters/.html' },
		{ name: 'Калифа', image: 'img/', link: 'characters/.html' },
		{ name: 'Айсберг', image: 'img/', link: 'characters/.html' },
		{ name: 'Каку', image: 'img/', link: 'characters/.html' },
		{ name: 'Замбай', image: 'img/', link: 'characters/.html' },
		{ name: 'Бруно', image: 'img/', link: 'characters/.html' },
		{ name: 'Луччи', image: 'img/', link: 'characters/.html' },
		{ name: 'Моджи', image: 'img/', link: 'characters/.html' },
		{ name: 'Френки', image: 'img/', link: 'characters/.html' },
		{ name: 'Киви', image: 'img/', link: 'characters/.html' },
		{ name: 'Том', image: 'img/', link: 'characters/.html' },
		{ name: 'Жоржи', image: 'img/', link: 'characters/.html' },
		{ name: 'Спандам', image: 'img/', link: 'characters/.html' },
		{ name: 'Стиви', image: 'img/', link: 'characters/.html' },
		{ name: 'Бушон', image: 'img/', link: 'characters/.html' },
		{ name: 'Тю Бон', image: 'img/', link: 'characters/.html' },
		{ name: 'Фанкфрид', image: 'img/', link: 'characters/.html' },
		{ name: 'Гоморра', image: 'img/', link: 'characters/.html' },
		{ name: 'Содом', image: 'img/', link: 'characters/.html' },
		{ name: 'Неро', image: 'img/', link: 'characters/.html' },
		{ name: 'Ванз', image: 'img/', link: 'characters/.html' },
		{ name: 'Джабура', image: 'img/', link: 'characters/.html' },
		{ name: 'Фукуро', image: 'img/', link: 'characters/.html' },
		{ name: 'Кумадори', image: 'img/', link: 'characters/.html' },
		{ name: 'Каши', image: 'img/', link: 'characters/.html' },
		{ name: 'Оймо', image: 'img/', link: 'characters/.html' },
		{ name: 'Кервиль', image: 'img/', link: 'characters/.html' },
		{ name: 'Бас', image: 'img/', link: 'characters/.html' },
		{ name: 'Принцесса', image: 'img/', link: 'characters/.html' },
		{ name: 'Клевер', image: 'img/', link: 'characters/.html' },
		{ name: 'Спандайн', image: 'img/', link: 'characters/.html' },
		{ name: 'Саул', image: 'img/', link: 'characters/.html' },
		{ name: 'Ольвия', image: 'img/', link: 'characters/.html' },
		{ name: 'Сакадзуки', image: 'img/', link: 'characters/.html' },
	],
	group3: [
		{ name: 'Онигумо', image: 'img/', link: 'characters/.html' },
		{ name: 'Ямакадзи', image: 'img/', link: 'characters/.html' },
		{ name: 'Доберман', image: 'img/', link: 'characters/.html' },
		{ name: 'Момонга', image: 'img/', link: 'characters/.html' },
		{ name: 'Стробери', image: 'img/', link: 'characters/.html' },
		{ name: 'Шу', image: 'img/', link: 'characters/.html' },
		{ name: 'Аттатян', image: 'img/', link: 'characters/.html' },
		{ name: 'Перона', image: 'img/', link: 'characters/.html' },
		{ name: 'Абсалом', image: 'img/', link: 'characters/.html' },
		{ name: 'Хогбак', image: 'img/', link: 'characters/.html' },
		{ name: 'Бухитяк', image: 'img/', link: 'characters/.html' },
		{ name: 'Синдри', image: 'img/', link: 'characters/.html' },
		{ name: 'Мокдональд', image: 'img/', link: 'characters/.html' },
		{ name: 'Рюма', image: 'img/', link: 'characters/.html' },
		{ name: 'Кумаси', image: 'img/', link: 'characters/.html' },
		{ name: 'Мория', image: 'img/', link: 'characters/.html' },
		{ name: 'Лола', image: 'img/', link: 'characters/.html' },
		{ name: 'Орз', image: 'img/', link: 'characters/.html' },
		{ name: 'Дюваль', image: 'img/', link: 'characters/.html' },
		{ name: 'Мотобаро', image: 'img/', link: 'characters/.html' },
		{ name: 'Шалулия', image: 'img/', link: 'characters/.html' },
		{ name: 'Росвард', image: 'img/', link: 'characters/.html' },
		{ name: 'Сэнтомару', image: 'img/', link: 'characters/.html' },
		{ name: 'Барт', image: 'img/', link: 'characters/.html' },
		{ name: 'Арудж', image: 'img/', link: 'characters/.html' },
		{ name: 'Апу', image: 'img/', link: 'characters/.html' },
		{ name: 'Дрейк', image: 'img/', link: 'characters/.html' },
		{ name: 'Капоне', image: 'img/', link: 'characters/.html' },
		{ name: 'Киллер', image: 'img/', link: 'characters/.html' },
		{ name: 'Хокинс', image: 'img/', link: 'characters/.html' },
		{ name: 'Шакуяку', image: 'img/', link: 'characters/.html' },
		{ name: 'Кид', image: 'img/', link: 'characters/.html' },
		{ name: 'Пенгвин', image: 'img/', link: 'characters/.html' },
		{ name: 'Бонни', image: 'img/', link: 'characters/.html' },
		{ name: 'Бепо', image: 'img/', link: 'characters/.html' },
		{ name: 'Ло', image: 'img/', link: 'characters/.html' },
		{ name: 'Чарлос', image: 'img/', link: 'characters/.html' },
		{ name: 'Хит', image: 'img/', link: 'characters/.html' },
		{ name: 'Борсалино', image: 'img/', link: 'characters/.html' },
		{ name: 'Пацифиста', image: 'img/', link: 'characters/.html' },
		{ name: 'Нён', image: 'img/', link: 'characters/.html' },
		{ name: 'Свит Пи', image: 'img/', link: 'characters/.html' },
		{ name: 'Афеландра', image: 'img/', link: 'characters/.html' },
		{ name: 'Маргарет', image: 'img/', link: 'characters/.html' },
		{ name: 'Саломея', image: 'img/', link: 'characters/.html' },
		{ name: 'Сандерсония', image: 'img/', link: 'characters/.html' },
		{ name: 'Хэнкок', image: 'img/', link: 'characters/.html' },
		{ name: 'Бакура', image: 'img/', link: 'characters/.html' },
		{ name: 'Юда', image: 'img/', link: 'characters/.html' },
		{ name: 'Тайгер', image: 'img/', link: 'characters/.html' },
		{ name: 'Тибани', image: 'img/', link: 'characters/.html' },
		{ name: 'Харедас', image: 'img/', link: 'characters/.html' },
		{ name: 'Минотавр', image: 'img/', link: 'characters/.html' },
		{ name: 'Магеллан', image: 'img/', link: 'characters/.html' },
		{ name: 'Сади', image: 'img/', link: 'characters/.html' },
		{ name: 'Инадзума', image: 'img/', link: 'characters/.html' },
		{ name: 'Иванков', image: 'img/', link: 'characters/.html' },
		{ name: 'Ширью', image: 'img/', link: 'characters/.html' },
		{ name: 'Кэролайн', image: 'img/', link: 'characters/.html' },
		{ name: 'Руж', image: 'img/', link: 'characters/.html' },
		{ name: 'Сквард', image: 'img/', link: 'characters/.html' },
		{ name: 'Бастилия', image: 'img/', link: 'characters/.html' },
		{ name: 'Далматин', image: 'img/', link: 'characters/.html' },
		{ name: 'Изо', image: 'img/', link: 'characters/.html' },
		{ name: 'Литл', image: 'img/', link: 'characters/.html' },
		{ name: 'Шот', image: 'img/', link: 'characters/.html' },
		{ name: 'Вульф', image: 'img/', link: 'characters/.html' },
		{ name: 'Писарро', image: 'img/', link: 'characters/.html' },
		{ name: 'Девон', image: 'img/', link: 'characters/.html' },
		{ name: 'Дадан', image: 'img/', link: 'characters/.html' },
		{ name: 'Магра', image: 'img/', link: 'characters/.html' },
		{ name: 'Догра', image: 'img/', link: 'characters/.html' },
		{ name: 'Сабо', image: 'img/', link: 'characters/.html' },
		{ name: 'Шоколя', image: 'img/', link: 'characters/.html' },
		{ name: 'Монблютен', image: 'img/', link: 'characters/.html' },
		{ name: 'Гицунэ', image: 'img/', link: 'characters/.html' },
		{ name: 'Торуко', image: 'img/', link: 'characters/.html' },
		{ name: 'Дрип', image: 'img/', link: 'characters/.html' },
		{ name: 'Блэк', image: 'img/', link: 'characters/.html' },
		{ name: 'Мандзяро', image: 'img/', link: 'characters/.html' },
		{ name: 'Кокоа', image: 'img/', link: 'characters/.html' },
		{ name: 'Карибу', image: 'img/', link: 'characters/.html' },
		{ name: 'Корибу', image: 'img/', link: 'characters/.html' },
		{ name: 'Альбион', image: 'img/', link: 'characters/.html' },
	],
	group4: [
		{ name: 'Суруме', image: 'img/chopper.jpg', link: 'characters/chopper.html' },
		{ name: 'Вандер', image: 'img/', link: 'characters/.html' },
		{ name: 'Вадацуми', image: 'img/', link: 'characters/.html' },
		{ name: 'Анкоро', image: 'img/', link: 'characters/.html' },
		{ name: 'Сора', image: 'img/', link: 'characters/.html' },
		{ name: 'Сейра', image: 'img/', link: 'characters/.html' },
		{ name: 'Кайрен', image: 'img/', link: 'characters/.html' },
		{ name: 'Джонс', image: 'img/', link: 'characters/.html' },
		{ name: 'Хирамера', image: 'img/', link: 'characters/.html' },
		{ name: 'Фукабоси', image: 'img/', link: 'characters/.html' },
		{ name: 'Рюбоси', image: 'img/', link: 'characters/.html' },
		{ name: 'Манбоси', image: 'img/', link: 'characters/.html' },
		{ name: 'Сярли', image: 'img/', link: 'characters/.html' },
		{ name: 'Сплаш', image: 'img/', link: 'characters/.html' },
		{ name: 'Сплатер', image: 'img/', link: 'characters/.html' },
		{ name: 'Нептун', image: 'img/', link: 'characters/.html' },
		{ name: 'Ширахоши', image: 'img/', link: 'characters/.html' },
		{ name: 'Аладин', image: 'img/', link: 'characters/.html' },
		{ name: 'Отохиме', image: 'img/', link: 'characters/.html' },
		{ name: 'Коала', image: 'img/', link: 'characters/.html' },
		{ name: 'Линлин', image: 'img/', link: 'characters/.html' },
		{ name: 'Пудинг', image: 'img/', link: 'characters/.html' },
		{ name: 'Нитро', image: 'img/', link: 'characters/.html' },
		{ name: 'Наполеон', image: 'img/', link: 'characters/.html' },
		{ name: 'Тамаго', image: 'img/', link: 'characters/.html' },
		{ name: 'Пекомс', image: 'img/', link: 'characters/.html' },
		{ name: 'Кинемон', image: 'img/', link: 'characters/.html' },
		{ name: 'Мотя', image: 'img/', link: 'characters/.html' },
		{ name: 'Синд', image: 'img/', link: 'characters/.html' },
		{ name: 'Комбу', image: 'img/', link: 'characters/.html' },
		{ name: 'Моне', image: 'img/', link: 'characters/.html' },
		{ name: 'Цезарь', image: 'img/', link: 'characters/.html' },
		{ name: 'Смайли', image: 'img/', link: 'characters/.html' },
		{ name: 'Верго', image: 'img/', link: 'characters/.html' },
		{ name: 'Гладиус', image: 'img/', link: 'characters/.html' },
		{ name: 'Детка 5', image: 'img/', link: 'characters/.html' },
		{ name: 'Сахарок', image: 'img/', link: 'characters/.html' },
		{ name: 'Лао Джи', image: 'img/', link: 'characters/.html' },
		{ name: 'Махвайс', image: 'img/', link: 'characters/.html' },
		{ name: 'Джора', image: 'img/', link: 'characters/.html' },
		{ name: 'Момоноске', image: 'img/', link: 'characters/.html' },
		{ name: 'Баффало', image: 'img/', link: 'characters/.html' },
		{ name: 'Диаманте', image: 'img/', link: 'characters/.html' },
		{ name: 'Пика', image: 'img/', link: 'characters/.html' },
		{ name: 'Требол', image: 'img/', link: 'characters/.html' },
		{ name: 'Канджиро', image: 'img/', link: 'characters/.html' },
		{ name: 'Пинк', image: 'img/', link: 'characters/.html' },
		{ name: 'Деллинджер', image: 'img/', link: 'characters/.html' },
		{ name: 'Кирос', image: 'img/', link: 'characters/.html' },
		{ name: 'Виола', image: 'img/', link: 'characters/.html' },
		{ name: 'Ребекка', image: 'img/', link: 'characters/.html' },
		{ name: 'Сай', image: 'img/', link: 'characters/.html' },
		{ name: 'Цинцзяо', image: 'img/', link: 'characters/.html' },
		{ name: 'Кавендиш', image: 'img/', link: 'characters/.html' },
		{ name: 'Викка', image: 'img/', link: 'characters/.html' },
		{ name: 'Бартоломео', image: 'img/', link: 'characters/.html' },
		{ name: 'Рику', image: 'img/', link: 'characters/.html' },
		{ name: 'Хак', image: 'img/', link: 'characters/.html' },
		{ name: 'Хайрудин', image: 'img/', link: 'characters/.html' },
		{ name: 'Идео', image: 'img/', link: 'characters/.html' },
		{ name: 'Кабу', image: 'img/', link: 'characters/.html' },
		{ name: 'Лео', image: 'img/', link: 'characters/.html' },
		{ name: 'Бобомба', image: 'img/', link: 'characters/.html' },
		{ name: 'Биан', image: 'img/', link: 'characters/.html' },
		{ name: 'Скарлетт', image: 'img/', link: 'characters/.html' },
		{ name: 'Фарул', image: 'img/', link: 'characters/.html' },
		{ name: 'Хоминг', image: 'img/', link: 'characters/.html' },
		{ name: 'Росинант', image: 'img/', link: 'characters/.html' },
		{ name: 'Кайдо', image: 'img/', link: 'characters/.html' },
		{ name: 'Тристан', image: 'img/', link: 'characters/.html' },
	],
	group5: [
		{ name: 'Чоппер', image: 'img/chopper.jpg', link: 'characters/chopper.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
		{ name: '', image: 'img/', link: 'characters/.html' },
	],
};

// Функция для изменения отображаемой группы персонажей
function changeGroup(group) {
	var charactersContainer = document.getElementById('charactersContainer');
	charactersContainer.innerHTML = ''; // Очищаем контейнер перед добавлением новых карточек

	// Перебираем персонажей выбранной группы и формируем HTML
	charactersData[group].forEach(function(character) {
		var cardHtml = `
				<div class="col mb-4">
						<div class="card text-bg-dark shadow-sm bg-body-tertiary position-relative overflow-hidden">
								<img src="${character.image}" class="img-fluid object-fit-cover" style="height: 300px;" alt="...">
								<div class="card-img-overlay d-flex align-items-end">
										<a href="${character.link}"><p class="card-title card-black stretched-link text-danger-hover">${character.name}</p></a>
								</div>
						</div>
				</div>
		`;

	charactersContainer.innerHTML += cardHtml; // Добавляем каждую карточку в контейнер
});
}

// Изначально отображаем первую группу при загрузке страницы
changeGroup('group1');